events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript application/wasm;

    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(js|css|wasm|dll|dat|json|png|jpg|svg|ico)$ {
            expires 1d;
            add_header Cache-Control "public, max-age=86400";
        }
    }
}
